//! Agent crate imports (auto-generated by ma-config, do not edit)
//!
//! Each `use` pulls in the crate, causing #[modular_agent] registrations
//! to be linked via the `inventory` crate.

use modular_agent_llm as _;
use modular_agent_std as _;
