// Ambient declaration for the build-time virtual module generated by
// vite-plugin-module-ui.js (registers module UI packages from ma-config.toml).
// Side-effect only — imported once from +layout.svelte.
declare module "virtual:module-ui";
