[package]
name = "modular-agent-desktop"
version = "0.19.0"
description = "Modular Agent Desktop Application"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "modular_agent_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
ctrlc = "3.4.5"
dirs = "6.0"
log = { workspace = true }
rand = "0.9"
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
tauri-plugin-store = "2"
tokio = { version = "1", features = ["full"] }
modular-agent-core = { workspace = true, features = ["mcp-server", "mcp-http-client"] }
tauri-plugin-modular-agent = { workspace = true }
modular-agent-lifelog = { path = "../../../custom_agents/modular-agent-lifelog", default-features = false, features = ["application", "screen"] }
modular-agent-llm = { workspace = true }
modular-agent-mattermost = { path = "../../../custom_agents/modular-agent-mattermost", default-features = false, features = ["image"] }
modular-agent-monty = { path = "../../../custom_agents/modular-agent-monty" }
modular-agent-slack = { path = "../../../custom_agents/modular-agent-slack" }
modular-agent-sqlx = { path = "../../../custom_agents/modular-agent-sqlx" }
modular-agent-std = { workspace = true }
modular-agent-web = { workspace = true }
modular-agent-zapcode = { path = "../../../custom_agents/modular-agent-zapcode" }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2.3"
tauri-plugin-window-state = "2"
