use std::fs;
use std::path::Path;

use toml_edit::{Array, DocumentMut, InlineTable, Item, Value};

use crate::app::AppKind;
use crate::config::{AgentEntry, AgentSource, BuildConfig};
use crate::registry::{self, KnownAgent, Registry};

/// Update the app's `Cargo.toml` with the selected agents as dependencies.
pub fn update_manifest(
    app: AppKind,
    config: &BuildConfig,
    registry: &Registry,
    root: &Path,
) -> Result<(), String> {
    let manifest_path = app.manifest_path(root);
    let original = fs::read_to_string(&manifest_path)
        .map_err(|e| format!("Failed to read {}: {e}", manifest_path.display()))?;

    let mut doc: DocumentMut = original
        .parse()
        .map_err(|e| format!("Failed to parse {}: {e}", manifest_path.display()))?;

    let deps = doc["dependencies"]
        .as_table_mut()
        .ok_or_else(|| format!("Missing [dependencies] in {}", manifest_path.display()))?;

    let stale: Vec<String> = deps
        .iter()
        .filter(|(key, _)| {
            key.starts_with("modular-agent-") || *key == "tauri-plugin-modular-agent"
        })
        .map(|(key, _)| key.to_string())
        .collect();
    for key in stale {
        deps.remove(&key);
    }

    // core and the plugin are in-tree and not selectable, so they are always
    // plain workspace dependencies.
    let mut core_dep = InlineTable::new();
    core_dep.insert("workspace", Value::from(true));
    let mut core_features = Array::new();
    for feature in app.core_features() {
        core_features.push(*feature);
    }
    core_dep.insert("features", Value::from(core_features));
    deps.insert(
        "modular-agent-core",
        Item::Value(Value::InlineTable(core_dep)),
    );

    if app.needs_plugin() {
        let mut plugin_dep = InlineTable::new();
        plugin_dep.insert("workspace", Value::from(true));
        deps.insert(
            "tauri-plugin-modular-agent",
            Item::Value(Value::InlineTable(plugin_dep)),
        );
    }

    for agent in &config.agents {
        let known = registry::find_by_name(&registry.agents, &agent.name);
        deps.insert(&agent.name, Item::Value(agent_dep_value(app, agent, known)));
    }

    fs::write(&manifest_path, doc.to_string())
        .map_err(|e| format!("Failed to write {}: {e}", manifest_path.display()))
}

/// The `[dependencies]` entry for one agent.
///
/// Out-of-tree agents are always path dependencies on their clone under
/// `custom_agents/`; a path inside the workspace makes the clone a workspace
/// member, so it shares this workspace's lock file and its copy of core.
fn agent_dep_value(app: AppKind, agent: &AgentEntry, known: Option<&KnownAgent>) -> Value {
    let custom_features = agent.crate_features.as_deref();

    if let Some(known) = known.filter(|k| k.in_tree) {
        let mut dep = InlineTable::new();
        match custom_features {
            // Feature overrides cannot ride on `workspace = true`: cargo
            // ignores a member's `default-features = false` when the workspace
            // entry does not set it. Spell the path out instead.
            Some(features) => {
                dep.insert("path", Value::from(rebase(app, &known.in_tree_path())));
                dep.insert("default-features", Value::from(false));
                dep.insert("features", Value::from(feature_array(features)));
            }
            None => {
                dep.insert("workspace", Value::from(true));
            }
        }
        return Value::InlineTable(dep);
    }

    let mut dep = source_to_inline_table(app, agent);
    // The wizard stores `None` when the selection equals the registry's
    // default_features. Unlike in-tree agents, where the workspace dependency
    // entry carries the right features, an out-of-tree dep line would fall back
    // to the crate's own defaults — which may differ (a crate can default to no
    // features while its catalog entry wants some enabled). Materialize the
    // registry defaults so both meanings of "default" agree.
    let features = custom_features.or_else(|| {
        known
            .map(|k| k.default_features.as_slice())
            .filter(|f| !f.is_empty())
    });
    if let Some(features) = features {
        dep.insert("default-features", Value::from(false));
        dep.insert("features", Value::from(feature_array(features)));
    }
    Value::InlineTable(dep)
}

fn feature_array(features: &[String]) -> Array {
    let mut array = Array::new();
    for feature in features {
        array.push(feature.as_str());
    }
    array
}

/// Generate the app's `agents.rs` with one import per selected agent.
pub fn generate_agents_rs(app: AppKind, config: &BuildConfig, root: &Path) -> Result<(), String> {
    let agents_path = app.agents_rs_path(root);

    let mut content = String::from(
        "//! Agent crate imports (auto-generated by ma-config, do not edit)\n\
         //!\n\
         //! Each `use` pulls in the crate, causing #[modular_agent] registrations\n\
         //! to be linked via the `inventory` crate.\n\n",
    );
    for agent in &config.agents {
        content.push_str(&format!("use {} as _;\n", agent.rust_crate_name()));
    }

    fs::write(&agents_path, content)
        .map_err(|e| format!("Failed to write {}: {e}", agents_path.display()))
}

/// Ensure the CLI's `main.rs` declares the generated agent module.
pub fn ensure_mod_agents(app: AppKind, root: &Path) -> Result<(), String> {
    let main_path = app.main_rs_path(root);
    let content = fs::read_to_string(&main_path)
        .map_err(|e| format!("Failed to read {}: {e}", main_path.display()))?;
    if content.contains("mod agents;") {
        return Ok(());
    }

    let mut lines: Vec<&str> = content.lines().collect();
    let after_use = lines
        .iter()
        .rposition(|line| line.starts_with("use "))
        .map(|i| i + 1)
        .unwrap_or(0);
    lines.insert(after_use, "mod agents;");
    lines.insert(after_use, "");

    fs::write(&main_path, lines.join("\n") + "\n")
        .map_err(|e| format!("Failed to write {}: {e}", main_path.display()))
}

fn source_to_inline_table(app: AppKind, agent: &AgentEntry) -> InlineTable {
    let mut dep = InlineTable::new();
    match &agent.source {
        Some(AgentSource::Workspace) => {
            dep.insert("workspace", Value::from(true));
        }
        // Config paths are workspace-root relative, but this table lands in the
        // app crate's manifest — rebase it like the in-tree override.
        Some(AgentSource::Path { path }) => {
            dep.insert("path", Value::from(rebase(app, path)));
        }
        // A registry agent carries no source: it is the clone under
        // custom_agents/, which validate_paths has already checked for.
        None => {
            dep.insert(
                "path",
                Value::from(rebase(app, &registry::clone_path(&agent.name))),
            );
        }
    }
    dep
}

/// Rewrite a workspace-root-relative path so it resolves from the app crate.
fn rebase(app: AppKind, path: &str) -> String {
    normalize_path(&format!("{}/{}", app.crate_dir_to_root(), path))
}

/// Normalize path separators: backslash -> forward slash for Cargo.toml compatibility.
fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Check that every out-of-tree agent points at a usable crate.
///
/// Both failures here produce a build that is worse than no build at all — a
/// missing crate, or a clone that drags in a second copy of core — so they stop
/// the run instead of warning.
pub fn validate_paths(config: &BuildConfig, root: &Path) -> Result<(), String> {
    let mut problems = Vec::new();

    for agent in &config.agents {
        let path = match &agent.source {
            Some(AgentSource::Workspace) => continue,
            Some(AgentSource::Path { path }) => path.clone(),
            None => registry::clone_path(&agent.name),
        };

        let manifest = root.join(&path).join("Cargo.toml");
        let Ok(manifest) = fs::read_to_string(&manifest) else {
            problems.push(format!(
                "{}: no crate at '{path}' — clone it (see custom_agents/README.md) or drop it \
                 from the selection",
                agent.name
            ));
            continue;
        };

        if !core_is_local(&manifest) {
            problems.push(format!(
                "{}: '{path}' still takes modular-agent-core from crates.io. Point it at the \
                 in-tree crate — `modular-agent-core = {{ path = \"../../crates/modular-agent-core\" }}` \
                 — because two linked copies of core mean two `inventory` registries, and the \
                 agents registered in the other one silently disappear.",
                agent.name
            ));
        }
    }

    if problems.is_empty() {
        return Ok(());
    }
    Err(format!(
        "Agent source problems:\n  - {}",
        problems.join("\n  - ")
    ))
}

/// Whether a crate's `modular-agent-core` dependency resolves inside this
/// workspace (a path, or the workspace entry the clone inherits as a member).
fn core_is_local(manifest: &str) -> bool {
    let Ok(manifest) = manifest.parse::<toml::Table>() else {
        return true; // Let cargo report a malformed manifest.
    };
    let Some(core) = manifest
        .get("dependencies")
        .and_then(|deps| deps.get("modular-agent-core"))
    else {
        return true; // Nothing to double-link.
    };
    core.get("path").is_some() || core.get("workspace").and_then(toml::Value::as_bool) == Some(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn registry() -> Registry {
        Registry {
            agents: vec![
                KnownAgent {
                    name: "modular-agent-std".into(),
                    description: "Standard agents".into(),
                    in_tree: true,
                    available_features: vec!["image".into(), "yaml".into()],
                    default_features: vec!["image".into(), "yaml".into()],
                    conflicts: vec![],
                    default_for: vec!["desktop".into(), "cli".into()],
                },
                KnownAgent {
                    name: "modular-agent-lifelog".into(),
                    description: "Lifelog agents".into(),
                    in_tree: false,
                    available_features: vec![],
                    default_features: vec![],
                    conflicts: vec![],
                    default_for: vec!["desktop".into()],
                },
                KnownAgent {
                    name: "modular-agent-example".into(),
                    description: "Example agents".into(),
                    in_tree: false,
                    available_features: vec!["basic".into(), "extra".into()],
                    default_features: vec!["extra".into()],
                    conflicts: vec![],
                    default_for: vec!["desktop".into()],
                },
            ],
        }
    }

    fn entry(name: &str, source: Option<AgentSource>, features: Option<Vec<String>>) -> AgentEntry {
        AgentEntry {
            name: name.into(),
            source,
            crate_features: features,
        }
    }

    fn scratch(label: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("ma-config-{}-{label}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn manifest_after(label: &str, app: AppKind, config: &BuildConfig) -> String {
        let dir = scratch(label);
        let manifest = app.manifest_path(&dir);
        fs::create_dir_all(manifest.parent().unwrap()).unwrap();
        fs::write(
            &manifest,
            "[dependencies]\nserde = \"1\"\nmodular-agent-gone = { git = \"stale\" }\n",
        )
        .unwrap();
        update_manifest(app, config, &registry(), &dir).unwrap();
        let out = fs::read_to_string(&manifest).unwrap();
        let _ = fs::remove_dir_all(&dir);
        out
    }

    #[test]
    fn in_tree_agents_become_workspace_dependencies() {
        let config = BuildConfig {
            agents: vec![entry(
                "modular-agent-std",
                Some(AgentSource::Workspace),
                None,
            )],
        };
        let out = manifest_after("in-tree", AppKind::Desktop, &config);

        assert!(out.contains("modular-agent-std = { workspace = true }"));
        assert!(out.contains(
            "modular-agent-core = { workspace = true, \
             features = [\"mcp-server\", \"mcp-http-client\"] }"
        ));
        assert!(out.contains("tauri-plugin-modular-agent = { workspace = true }"));
        // Agents dropped from the selection lose their dependency line.
        assert!(!out.contains("modular-agent-gone"));
    }

    #[test]
    fn in_tree_feature_overrides_spell_out_the_path() {
        let config = BuildConfig {
            agents: vec![entry(
                "modular-agent-std",
                Some(AgentSource::Workspace),
                Some(vec!["yaml".into()]),
            )],
        };
        let out = manifest_after("in-tree-features", AppKind::Cli, &config);

        assert!(out.contains(
            "modular-agent-std = { path = \"../../crates/modular-agent-std\", \
             default-features = false, features = [\"yaml\"] }"
        ));
        // The CLI does not link the Tauri plugin.
        assert!(!out.contains("tauri-plugin-modular-agent"));
    }

    #[test]
    fn unregistered_agent_paths_are_rebased_to_the_app_manifest() {
        let config = BuildConfig {
            agents: vec![entry(
                "modular-agent-custom",
                Some(AgentSource::Path {
                    // Backslashes from a Windows path are normalized for Cargo.
                    path: "custom_agents\\modular-agent-custom".into(),
                }),
                None,
            )],
        };
        let out = manifest_after("custom-path", AppKind::Desktop, &config);

        assert!(out.contains(
            "modular-agent-custom = { path = \"../../../custom_agents/modular-agent-custom\" }"
        ));
    }

    #[test]
    fn registry_agents_resolve_to_their_custom_agents_clone() {
        let config = BuildConfig {
            agents: vec![entry("modular-agent-lifelog", None, None)],
        };
        let out = manifest_after("clone-path", AppKind::Desktop, &config);

        assert!(out.contains(
            "modular-agent-lifelog = { path = \"../../../custom_agents/modular-agent-lifelog\" }"
        ));
        assert!(!out.contains("git ="));
    }

    #[test]
    fn registry_default_features_materialize_for_out_of_tree_deps() {
        let config = BuildConfig {
            agents: vec![entry("modular-agent-example", None, None)],
        };
        let out = manifest_after("registry-defaults", AppKind::Cli, &config);

        assert!(out.contains(
            "modular-agent-example = { path = \"../../custom_agents/modular-agent-example\", \
             default-features = false, features = [\"extra\"] }"
        ));
    }

    fn validate_with_clone(label: &str, core_dep: &str) -> Result<(), String> {
        let dir = scratch(label);
        let crate_dir = dir.join("custom_agents/modular-agent-lifelog");
        fs::create_dir_all(&crate_dir).unwrap();
        fs::write(
            crate_dir.join("Cargo.toml"),
            format!("[dependencies]\n{core_dep}\n"),
        )
        .unwrap();

        let config = BuildConfig {
            agents: vec![entry("modular-agent-lifelog", None, None)],
        };
        let result = validate_paths(&config, &dir);
        let _ = fs::remove_dir_all(&dir);
        result
    }

    /// The same message has to cover a selection whose registry entry is gone
    /// too: the catalog is now built from the clones, so deleting a clone
    /// deletes its entry.
    #[test]
    fn a_missing_clone_points_at_the_custom_agents_readme() {
        let dir = scratch("missing-clone");
        let config = BuildConfig {
            agents: vec![entry("modular-agent-lifelog", None, None)],
        };
        let err = validate_paths(&config, &dir).unwrap_err();
        let _ = fs::remove_dir_all(&dir);

        assert!(err.contains("no crate at 'custom_agents/modular-agent-lifelog'"));
        assert!(err.contains("custom_agents/README.md"));
    }

    #[test]
    fn a_clone_still_on_the_published_core_is_rejected() {
        let err = validate_with_clone("stale-core", "modular-agent-core = \"0.27.0\"").unwrap_err();
        assert!(err.contains("crates.io"));

        validate_with_clone(
            "path-core",
            "modular-agent-core = { path = \"../../crates/modular-agent-core\" }",
        )
        .unwrap();
    }
}
