[package]
name = "modular-agent-llm"
version = "0.15.0"
description = "LLM Agents for Modular Agent"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
eventsource-stream = { version = "0.2", optional = true }
futures = { version = "0.3.31", optional = true }
icu_normalizer = "2.1.1"
im = { workspace = true }
log = { workspace = true }
photon-rs = { version = "0.3.3", optional = true }
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls", "json", "stream"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
text-splitter = { version = "0.29.3", features = ["tokenizers"] }
tokenizers = { version = "0.22.2", features = ["http"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"
uuid = { version = "1.18.1", features = ["v4"] }

modular-agent-core = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
modular-agent-core = { workspace = true, features = ["test-utils"] }

[features]
default = ["image", "claude", "ollama", "openai"]
claude = ["reqwest", "eventsource-stream", "futures"]
image = ["photon-rs"]
ollama = ["reqwest", "futures"]
openai = ["reqwest", "eventsource-stream", "futures"]
