[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-new-patch",
    "allow-add-patch",
    "allow-add-patch-with-name",
    "allow-remove-patch",
    "allow-start-patch",
    "allow-stop-patch",
    "allow-open-patch-from-file",
    "allow-save-patch",
    "allow-get-patch-spec",
    "allow-update-patch-spec",
    "allow-get-patch-info",
    "allow-get-patch-infos",
    "allow-get-module-definition",
    "allow-get-module-definitions",
    "allow-get-module-spec",
    "allow-update-module-spec",
    "allow-new-module-spec",
    "allow-add-module",
    "allow-remove-module",
    "allow-add-connection",
    "allow-remove-connection",
    "allow-add-modules-and-connections",
    "allow-start-module",
    "allow-stop-module",
    "allow-get-module-statuses",
    "allow-set-module-configs",
    "allow-get-global-configs",
    "allow-get-global-configs-map",
    "allow-set-global-configs",
    "allow-set-global-configs-map",
    "allow-write-external-input",
]
