[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-new-patch",
    "allow-add-patch",
    "allow-add-patch-with-name",
    "allow-remove-patch",
    "allow-start-patch",
    "allow-stop-patch",
    "allow-open-patch-from-file",
    "allow-save-patch",
    "allow-get-patch-spec",
    "allow-update-patch-spec",
    "allow-get-patch-info",
    "allow-get-patch-infos",
    "allow-get-agent-definition",
    "allow-get-agent-definitions",
    "allow-get-agent-spec",
    "allow-update-agent-spec",
    "allow-new-agent-spec",
    "allow-add-agent",
    "allow-remove-agent",
    "allow-add-connection",
    "allow-remove-connection",
    "allow-add-agents-and-connections",
    "allow-start-agent",
    "allow-stop-agent",
    "allow-set-agent-configs",
    "allow-get-global-configs",
    "allow-get-global-configs-map",
    "allow-set-global-configs",
    "allow-set-global-configs-map",
    "allow-write-external-input",
]
