[package]
name = "modular-agent-cli"
version = "0.5.0"
description = "CLI runner for Modular Agent"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ma"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "io-util", "io-std", "signal", "sync"] }
modular-agent-core = { workspace = true, features = ["mcp-server", "mcp-http-client"] }
modular-agent-llm = { workspace = true }
modular-agent-std = { workspace = true }
