[package]
name = "modular-agent-cli"
version = "0.4.1"
description = "CLI runner for Modular Agent"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ma"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "io-util", "io-std", "signal", "sync"] }
modular-agent-core = { workspace = true, features = ["mcp-server", "mcp-http-client"] }
modular-agent-llm = { workspace = true }
modular-agent-slack = { path = "../../custom_agents/modular-agent-slack" }
modular-agent-sqlx = { path = "../../custom_agents/modular-agent-sqlx" }
modular-agent-std = { workspace = true }
modular-agent-web = { path = "../../custom_agents/modular-agent-web", default-features = false, features = ["fetch-url", "html-scraper", "html-to-markdown", "searxng", "yt-transcript"] }
