const COMMANDS: &[&str] = &[
    "new_patch",
    "add_patch",
    "add_patch_with_name",
    "remove_patch",
    "start_patch",
    "stop_patch",
    "open_patch_from_file",
    "save_patch",
    "get_patch_spec",
    "update_patch_spec",
    "get_patch_info",
    "get_patch_infos",
    "get_module_definition",
    "get_module_definitions",
    "get_module_spec",
    "update_module_spec",
    "new_module_spec",
    "add_module",
    "remove_module",
    "add_connection",
    "remove_connection",
    "add_modules_and_connections",
    "start_module",
    "stop_module",
    "get_module_statuses",
    "set_module_configs",
    "get_global_configs",
    "get_global_configs_map",
    "set_global_configs",
    "set_global_configs_map",
    "write_external_input",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
