const COMMANDS: &[&str] = &[
    "get_agent_definition",
    "get_agent_definitions",
    "get_agent_spec",
    "update_agent_spec",
    "get_agent_stream_info",
    "get_agent_stream_infos",
    "get_agent_stream_spec",
    "update_agent_stream_spec",
    "new_agent_stream",
    "rename_agent_stream",
    "unique_stream_name",
    "add_agent_stream",
    "remove_agent_stream",
    "add_agents_and_channels",
    "start_agent_stream",
    "stop_agent_stream",
    "new_agent_spec",
    "add_agent",
    "remove_agent",
    "add_channel",
    "remove_channel",
    "start_agent",
    "stop_agent",
    "write_board",
    "set_agent_configs",
    "get_global_configs",
    "get_global_configs_map",
    "set_global_configs",
    "set_global_configs_map",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
