const COMMANDS: &[&str] = &[
    "new_patch",
    "add_patch",
    "add_patch_with_name",
    "remove_patch",
    "start_patch",
    "stop_patch",
    "open_patch_from_file",
    "save_patch",
    "get_patch_spec",
    "update_patch_spec",
    "get_patch_info",
    "get_patch_infos",
    "get_agent_definition",
    "get_agent_definitions",
    "get_agent_spec",
    "update_agent_spec",
    "new_agent_spec",
    "add_agent",
    "remove_agent",
    "add_connection",
    "remove_connection",
    "add_agents_and_connections",
    "start_agent",
    "stop_agent",
    "set_agent_configs",
    "get_global_configs",
    "get_global_configs_map",
    "set_global_configs",
    "set_global_configs_map",
    "write_external_input",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
